= Open Document backend for Asciidoctor
:xrefstyle: short
:sectnums:
:stem:
:mathematical-format: svg
:doctype: book

== About

Open Document backend for Asciidoctor allows to convert asciidoc documentation into fodt (plain Open Document) format. It relies on https://docs.asciidoctor.org/home/[Asciidoctor project].

Fodt file may be converted with https://www.libreoffice.org/[LibreOffice] into pdf, odt, docx, doc etc.

Examples (built automatically as a part of CI routine):

* https://github.com/CourseOrchestra/asciidoctor-open-document/blob/main/test/test_cases/stew/test.adoc[source asciidoc file];
* https://courseorchestra.github.io/asciidoctor-open-document/test.fodt[fodt file] (indexes are not updated);
* https://courseorchestra.github.io/asciidoctor-open-document/test.odt[odt file];
* https://courseorchestra.github.io/asciidoctor-open-document/test.pdf[pdf file];
* https://courseorchestra.github.io/asciidoctor-open-document/test.docx[docx file] -- yes, sometimes messy, but generally not so bad and there is always a possibility to simplify conversion rules and tailor them to the needs of the exact project.

The asciidoctor-open-document backend can be extended in the following ways:

* custom fodt template. Allows to customize paragraph properties, text properties, page properties (orientation, header, footer and like), list properties, table properties. Custom fodt template can contain title page or any before/after content;
* custom slim templates;
* custom xml-content preprocessor;
* custom Open Document style setters.

== Usage

=== With docker

* Download and unzip project, manually or with:
+
----
wget https://github.com/CourseOrchestra/asciidoctor-open-document/archive/refs/heads/dev.zip -O temp.zip && unzip temp.zip && rm temp.zip
----

* Build docker image
+
----
build/build_image.sh
----

* Convert adoc to preliminary Open Document content file
+
The following steps assume that asciidoc file `test.adoc` is in the `/my-adoc` directory. As a result we want to get `test.fodt` and `test.pdf`.
+
----
docker run -it -v /my-adoc:/documents/ asciidoctor-od a-od-pre -r asciidoctor-mathematical -r asciidoctor-diagram test.adoc -o pre.xml
----
+
Here `asciidoctor-mathematical` and `asciidoctor-diagram` extensions are used.

* Convert preliminary Open Document content file to fodt
+
----
docker run -it -v /my-adoc:/documents/ asciidoctor-od a-od-out -c /usr/local/a-od/a-od-my/my-cp-example.rb -i pre.xml -o test.fodt
----
+
Here the custom library is used. It contains examples of custom features: positioning equation number, paragraph alignment role, code highlighting, positioning admonitions inside of the list element.

* Convert fodt to odt, pdf, docx etc.
+
For deployment in this project https://github.com/hannesdejager/docker-libreoffice-api[LibreOffice Headless with API in Docker] is used (<<build>>). It contains LibreOffice and https://github.com/dagwieers/unoconv[Universal Office Converter (unoconv)]. Unoconv updates indexes (table of contents, figure index, table index and so on) before converting.
+
.build/build.sh (LibreOffice conversion part)
[[build]]
----
echo convert to pdf, odt, docx
docker run -d --name libreoffice -p 8100:8100 hdejager/libreoffice-api
sleep 3
docker cp target/stew/test.fodt libreoffice:/tmp/test.fodt
docker exec -i libreoffice unoconv --connection \
    'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ComponentContext' \
    -f pdf /tmp/test.fodt
docker exec -i libreoffice unoconv --connection \
    'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ComponentContext' \
    -f odt /tmp/test.fodt
docker exec -i libreoffice unoconv --connection \
    'socket,host=127.0.0.1,port=8100,tcpNoDelay=1;urp;StarOffice.ComponentContext' \
    -f docx /tmp/test.fodt
docker cp libreoffice:/tmp/test.odt target/stew
docker cp libreoffice:/tmp/test.pdf target/stew
docker cp libreoffice:/tmp/test.docx target/stew
docker kill libreoffice
docker rm libreoffice
cp target/stew/test.pdf target/out
cp target/stew/test.odt target/out
cp target/stew/test.docx target/out
cp target/stew/test.fodt target/out
----

=== As a ruby script

Conversion consists of 2 steps.

. Convert adoc to preliminary content file
. Convert preliminary content file to fodt

==== Convert adoc to preliminary content file

Conversion to preliminary content file is done by the standard `asciidoctor` command with a slim template (slim folder of a source code).

----
asciidoctor -T [path to slim] -b fodt asciidoc_file.adoc
----

There is a wrapper `a-od-pre` in docker image. Use it like a normal `asciidoctor` command. It just sets slim template and backend.


==== Convert preliminary content file to fodt

Conversion to final fodt file is done with the `asciidoctor-od.rb` script.

----
ruby [path to script]/a-od-producer.rb -i [prelimenary content file] -o [final file] -c [custom process library] -f [fodt template]
----

There is a wrapper `a-od-out` in docker image. It just runs ruby with `a-od-producer.rb`.

== How does it work

:leveloffset: + 1

== Setting predefined styles

"`You should create documentation in Word, RIGHT WAY`". 

MS Word as well as Open Office suggest that each element should have only one style. That greatly contradicts to the concept of cascaded styles (CSS), but makes things easier. If we can define such a unique style for text or paragraph, then we need nothing more.

It is always the case with list styles, but sometimes with text or less often paragraph styles.

StyleSubstitor just sets the predefined style for certain elements.

Here we may also do any xml preprocessing. Change the order of elements, insert custom elements. As we do it with xml, such preprocessing is extremely fast.

To extend setting predefined styles routine just make a descendant of `StyleSubstitutor` in your custom library.

== `Automatic styles` calculation

If you add you custom formatting to any paragraph Open Office simply generates `automatic style` that references parent (predefined style) and adds properties. Thee properties add or replace predefined style formatting.

Templating technology can't generate styles, but this converter adds formatting hints to the name of the style.  `AutoStyleSetter` transforms this hint into `automatic styles`.

`BasicPropSetSorter` chooses the right property setter class and property setter class sets parent (predefined) class and additional properties.

To extend style substitution just inherit from any property setter class, for example `BasicBlockImageParagraph`. Or from the basic sorter class `BasicPropSetSorter`.

All methods should start with `h_`.


:leveloffset!:

=== Customizing fodt template

* Only part of template that is situated between paragraphs, containing text `<asciidoctor-od>`, is replaced with the content of the asciidoctor file. This allows to make, for example, title pages.
* Asciidoc document attributes like title, subtitle, author etc. can be used via Open Document variable-set fields. The content of these fields is taken from asciidoc document attributes. For now only text variable-set fields are supported.
* Out of the box converter supports only two page styles (for portrait and landscape). This can be easily extended by custom conversion library.

== Not implemented

=== Not implemented elements

----
audio
dlist
inline_break
inline_button
inline_indexterm
inline_kbd
inline_menu
listing
open
page_break
pass
quote
section (no special processing for special sections)
sidebar
thematic_break
toc (for now relied on fodt template)
verse
video
----

=== Backend variables

Backend variables are set as global variables. They start with `def` prefix.

They can now be overriden only in custom library, but the ability to set them as document attributes is in the TODO-list.

:leveloffset: + 1

== Table properties

* `frame` and `grid` are implemented only if (1) both are none, (2) `frame` is `topbot` and `grid` is `rows`, (3) `frame` is `sides` and `grid` is `cols`
* `float`
* `width` (always `100%`)
* `options = autowidth`


== Frame usage

Admonitions and examples are created with the help of a frame. 

Frame width in Open Document format can't be defined in relation to paragraph, only paragraph area. So in lists frames will start from the left page margin.

As frames are aligned to right, it is possible to introduce some attribute that would decrease frame width. The example is in the `a-od-my` custom library of this project: list-level1-admonition.

IMPORTANT: Frames don't flow across pages


:leveloffset!:

== Additional features

:leveloffset: + 1

== Image attributes

* rectfit -- dimensions to fit image in like `100x50mm`. Only mm unit is supported
* srcdpi -- resolution of the source image. Usually when we add something to our diagram (like new process to the process diagram), the dimensions of the image change, but resolution doesn't change. Default -- 100 dpi.
* svgunit -- units, in which svg dimensions are defined

This attribute doesn't eliminate the need to have a set of image for each resolution, but for simple situation it is quite enough.

If `rectfit` is not defined in inline images it is assumed from the following attributes:

* def_100_percent_mm -- width
* def_inline_height_mm -- height

== Page orientation

Page orientation is regulated by special roles: portrait, landscape.

The role can be applied to paragraph, section and caption (table, figure, list, example) elements.

NOTE: Page orientation roles switch orientation for all elements to the end of the document. It can be switched back starting at any supported element


:leveloffset!: