#!/bin/bash

file_name=$1
output_format="pdf"
template_key=""

i=0
for var in "$@"
do
    ((i=i+1))
    if [ "$var" = "--asciidoctor" ]; then
      break
    fi
    aod_arg_count=$i
done

if [ "$aod_arg_count" -gt 1 ]; then
  output_format=$2
fi

if [ "$aod_arg_count" -gt 2 ]; then
  template_key=" -f $3"
fi

if [ "$aod_arg_count" -gt 3 ]; then
  custom_lib=" -c $4"
fi

# get only asciidoctor params
shift $aod_arg_count
shift 1

a-od-pre -r asciidoctor-mathematical -r asciidoctor-diagram $file_name -b fodt -o pre.xml "$@"
a-od-out -i pre.xml -o ${file_name%.*}.fodt_ $template_key $custom_lib
java -jar /usr/local/a-od/lo-kts-converter.main.jar -f $output_format -i ${file_name%.*}.fodt_

rm pre.xml
rm ${file_name%.*}.fodt_
