#!/bin/bash

file_name=$1
output_format="pdf"
template_key=""

if [ $# -gt 1 ]; then
  output_format=$2
fi

if [ $# -gt 2 ]; then
  template_key=" -f $3"
fi

if [ $# -gt 3 ]; then
  custom_lib=" -c $4"
fi

a-od-pre -r asciidoctor-mathematical -r asciidoctor-diagram $file_name -b fodt -o pre.xml
a-od-out -i pre.xml -o ${file_name%.*}.fodt_ $template_key $custom_lib
java -jar lo-kts-converter.main.jar -f $2 -i ${file_name%.*}.fodt_

rm pre.xml
rm ${file_name%.*}.fodt_
