= Open Document backend for Asciidoctor
:toc: left

== About

include::../README.adoc[tag=about]

== Usage

include::../README.adoc[tag=usage]

== How does it work

include::../lib/a-od-producer/asciidoctor-od.rb[tag = algorithm_description, leveloffset =+ 1]

=== Customizing fodt template

* Only part of template that is situated between paragraphs, containing text `<asciidoctor-od>`, is replaced with the content of the asciidoctor file. This allows to make, for example, title pages.
* Asciidoc document attributes like title, subtitle, author etc. can be used via Open Document variable-set fields. The content of these fields is taken from asciidoc document attributes. For now only text variable-set fields are supported.
* Out of the box converter supports only two page styles (for portrait and landscape). This can be easily extended by custom conversion library.

== Not implemented

=== Not implemented elements

----
audio
dlist
inline_button
inline_indexterm
inline_kbd
inline_menu
listing
open
page_break
pass
quote
section (no special processing for special sections)
sidebar
thematic_break
toc (for now relied on fodt template)
verse
video
----

=== Backend variables

Backend variables are set as global variables. They start with `def` prefix.

They can now be overriden only in custom library, but the ability to set them as document attributes is in the TODO-list.

include::../lib/a-od-producer/asciidoctor-od.rb[tag = notimplemented, leveloffset =+ 1]

== Additional features

include::../lib/a-od-producer/asciidoctor-od.rb[tag = plusfeatures, leveloffset =+ 1]
